### ISSUE TITLE
Login android to django to github

### ISSUE THREAD

**Issue by Yonimdo** [MoodyUser/9GAG#13]

**Comment by Yonimdo** [comment]
https://developer.github.com/guides/basics-of-authentication/#registering-your-app

**Comment by Yonimdo** [comment]
funny https://gist.github.com/strukturedkaos/1718308

https://gist.github.com/coyote240/f79b0745f98e5be71a71

https://gist.github.com/TomTasche/5665497

**Comment by Yonimdo** [comment]
https://github.com/gitskarios/GithubAndroidSdk

**Comment by MoodyUser** [comment]
lethargicpanda.tumblr.com/post/14784695735/oauth-login-on-your-android-app-the-github

**Comment by Yonimdo** [comment]
1e7546850608522f3004884fa9d377f282bfde95
